# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\WPy64-3740\SEBASTES\application\dialogs\ui\AutoSettingsDlg.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_autoSettingsDlg(object):
    def setupUi(self, autoSettingsDlg):
        autoSettingsDlg.setObjectName("autoSettingsDlg")
        autoSettingsDlg.resize(400, 500)
        self.formLayout_2 = QtWidgets.QFormLayout(autoSettingsDlg)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout)
        self.label1 = QtWidgets.QLabel(autoSettingsDlg)
        self.label1.setText("")
        self.label1.setObjectName("label1")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label1)
        self.lineEdit1 = QtWidgets.QLineEdit(autoSettingsDlg)
        self.lineEdit1.setObjectName("lineEdit1")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit1)
        self.label2 = QtWidgets.QLabel(autoSettingsDlg)
        self.label2.setText("")
        self.label2.setObjectName("label2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label2)
        self.lineEdit2 = QtWidgets.QLineEdit(autoSettingsDlg)
        self.lineEdit2.setObjectName("lineEdit2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit2)
        self.label3 = QtWidgets.QLabel(autoSettingsDlg)
        self.label3.setText("")
        self.label3.setObjectName("label3")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label3)
        self.lineEdit3 = QtWidgets.QLineEdit(autoSettingsDlg)
        self.lineEdit3.setObjectName("lineEdit3")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit3)
        self.label4 = QtWidgets.QLabel(autoSettingsDlg)
        self.label4.setText("")
        self.label4.setObjectName("label4")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label4)
        self.lineEdit4 = QtWidgets.QLineEdit(autoSettingsDlg)
        self.lineEdit4.setObjectName("lineEdit4")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit4)
        self.label5 = QtWidgets.QLabel(autoSettingsDlg)
        self.label5.setText("")
        self.label5.setObjectName("label5")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label5)
        self.lineEdit5 = QtWidgets.QLineEdit(autoSettingsDlg)
        self.lineEdit5.setObjectName("lineEdit5")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit5)
        self.label6 = QtWidgets.QLabel(autoSettingsDlg)
        self.label6.setText("")
        self.label6.setObjectName("label6")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label6)
        self.lineEdit6 = QtWidgets.QLineEdit(autoSettingsDlg)
        self.lineEdit6.setObjectName("lineEdit6")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit6)
        self.label7 = QtWidgets.QLabel(autoSettingsDlg)
        self.label7.setText("")
        self.label7.setObjectName("label7")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label7)
        self.lineEdit7 = QtWidgets.QLineEdit(autoSettingsDlg)
        self.lineEdit7.setObjectName("lineEdit7")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit7)
        self.label8 = QtWidgets.QLabel(autoSettingsDlg)
        self.label8.setText("")
        self.label8.setObjectName("label8")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label8)
        self.lineEdit8 = QtWidgets.QLineEdit(autoSettingsDlg)
        self.lineEdit8.setObjectName("lineEdit8")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit8)
        self.label9 = QtWidgets.QLabel(autoSettingsDlg)
        self.label9.setText("")
        self.label9.setObjectName("label9")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label9)
        self.lineEdit9 = QtWidgets.QLineEdit(autoSettingsDlg)
        self.lineEdit9.setObjectName("lineEdit9")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lineEdit9)
        self.label10 = QtWidgets.QLabel(autoSettingsDlg)
        self.label10.setText("")
        self.label10.setObjectName("label10")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label10)
        self.lineEdit10 = QtWidgets.QLineEdit(autoSettingsDlg)
        self.lineEdit10.setObjectName("lineEdit10")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.lineEdit10)
        self.label11 = QtWidgets.QLabel(autoSettingsDlg)
        self.label11.setText("")
        self.label11.setObjectName("label11")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label11)
        self.lineEdit11 = QtWidgets.QLineEdit(autoSettingsDlg)
        self.lineEdit11.setObjectName("lineEdit11")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.lineEdit11)
        self.frame = QtWidgets.QFrame(autoSettingsDlg)
        self.frame.setMinimumSize(QtCore.QSize(0, 51))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancelBtn = QtWidgets.QPushButton(self.frame)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)
        self.saveBtn = QtWidgets.QPushButton(self.frame)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout.addWidget(self.saveBtn)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.frame)
        self.label0 = QtWidgets.QLabel(autoSettingsDlg)
        self.label0.setText("")
        self.label0.setObjectName("label0")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label0)
        self.lineEdit0 = QtWidgets.QLineEdit(autoSettingsDlg)
        self.lineEdit0.setObjectName("lineEdit0")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit0)
        self.lineEdit12 = QtWidgets.QLineEdit(autoSettingsDlg)
        self.lineEdit12.setObjectName("lineEdit12")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.lineEdit12)
        self.label12 = QtWidgets.QLabel(autoSettingsDlg)
        self.label12.setText("")
        self.label12.setObjectName("label12")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label12)
        self.lineEdit13 = QtWidgets.QLineEdit(autoSettingsDlg)
        self.lineEdit13.setObjectName("lineEdit13")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.lineEdit13)
        self.label13 = QtWidgets.QLabel(autoSettingsDlg)
        self.label13.setText("")
        self.label13.setObjectName("label13")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label13)
        self.lineEdit14 = QtWidgets.QLineEdit(autoSettingsDlg)
        self.lineEdit14.setObjectName("lineEdit14")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.lineEdit14)
        self.label14 = QtWidgets.QLabel(autoSettingsDlg)
        self.label14.setText("")
        self.label14.setObjectName("label14")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label14)

        self.retranslateUi(autoSettingsDlg)
        QtCore.QMetaObject.connectSlotsByName(autoSettingsDlg)

    def retranslateUi(self, autoSettingsDlg):
        _translate = QtCore.QCoreApplication.translate
        autoSettingsDlg.setWindowTitle(_translate("autoSettingsDlg", "Dialog"))
        self.cancelBtn.setText(_translate("autoSettingsDlg", "Cancel"))
        self.saveBtn.setText(_translate("autoSettingsDlg", "Save"))
