# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\SEBASTES\SEBASTES_Python-3.7\applications\SEBASTES\application\dialogs\ui\ExportProfileDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_exportProfileDlg(object):
    def setupUi(self, exportProfileDlg):
        exportProfileDlg.setObjectName("exportProfileDlg")
        exportProfileDlg.resize(333, 186)
        self.verticalLayout = QtWidgets.QVBoxLayout(exportProfileDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(exportProfileDlg)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.importRadio = QtWidgets.QRadioButton(self.groupBox)
        self.importRadio.setObjectName("importRadio")
        self.horizontalLayout_2.addWidget(self.importRadio)
        self.exportRadio = QtWidgets.QRadioButton(self.groupBox)
        self.exportRadio.setObjectName("exportRadio")
        self.horizontalLayout_2.addWidget(self.exportRadio)
        self.verticalLayout.addWidget(self.groupBox)
        self.selProfilesBtn = QtWidgets.QPushButton(exportProfileDlg)
        self.selProfilesBtn.setObjectName("selProfilesBtn")
        self.verticalLayout.addWidget(self.selProfilesBtn)
        self.selSpcCollectionsBtn = QtWidgets.QPushButton(exportProfileDlg)
        self.selSpcCollectionsBtn.setObjectName("selSpcCollectionsBtn")
        self.verticalLayout.addWidget(self.selSpcCollectionsBtn)
        self.selMetaGroupsBtn = QtWidgets.QPushButton(exportProfileDlg)
        self.selMetaGroupsBtn.setObjectName("selMetaGroupsBtn")
        self.verticalLayout.addWidget(self.selMetaGroupsBtn)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.okBtn = QtWidgets.QPushButton(exportProfileDlg)
        self.okBtn.setObjectName("okBtn")
        self.horizontalLayout.addWidget(self.okBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(exportProfileDlg)
        QtCore.QMetaObject.connectSlotsByName(exportProfileDlg)

    def retranslateUi(self, exportProfileDlg):
        _translate = QtCore.QCoreApplication.translate
        exportProfileDlg.setWindowTitle(_translate("exportProfileDlg", "Import Export Profiles"))
        self.groupBox.setTitle(_translate("exportProfileDlg", "Action"))
        self.importRadio.setText(_translate("exportProfileDlg", "Import"))
        self.exportRadio.setText(_translate("exportProfileDlg", "Export"))
        self.selProfilesBtn.setText(_translate("exportProfileDlg", "Select Profiles"))
        self.selSpcCollectionsBtn.setText(_translate("exportProfileDlg", "Select Species Collections"))
        self.selMetaGroupsBtn.setText(_translate("exportProfileDlg", "Select Metadata Groups"))
        self.okBtn.setText(_translate("exportProfileDlg", "Done"))
