# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\SEBASTES\SEBASTES_Python-3.7\applications\SEBASTES\application\dialogs\ui\GridSetupDlg.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gridSetupDlg(object):
    def setupUi(self, gridSetupDlg):
        gridSetupDlg.setObjectName("gridSetupDlg")
        gridSetupDlg.resize(398, 242)
        self.verticalLayout = QtWidgets.QVBoxLayout(gridSetupDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(gridSetupDlg)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.gridSizeBox = QtWidgets.QComboBox(gridSetupDlg)
        self.gridSizeBox.setObjectName("gridSizeBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gridSizeBox)
        self.label_4 = QtWidgets.QLabel(gridSetupDlg)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineThicknessBox = QtWidgets.QComboBox(gridSetupDlg)
        self.lineThicknessBox.setObjectName("lineThicknessBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineThicknessBox)
        self.label_3 = QtWidgets.QLabel(gridSetupDlg)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.randomCheck = QtWidgets.QCheckBox(gridSetupDlg)
        self.randomCheck.setText("")
        self.randomCheck.setObjectName("randomCheck")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.randomCheck)
        self.label = QtWidgets.QLabel(gridSetupDlg)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.gridlineColorLabel = QtWidgets.QLabel(gridSetupDlg)
        self.gridlineColorLabel.setMinimumSize(QtCore.QSize(51, 0))
        self.gridlineColorLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.gridlineColorLabel.setText("")
        self.gridlineColorLabel.setObjectName("gridlineColorLabel")
        self.horizontalLayout_15.addWidget(self.gridlineColorLabel)
        self.gridlineColorBtn = QtWidgets.QPushButton(gridSetupDlg)
        self.gridlineColorBtn.setObjectName("gridlineColorBtn")
        self.horizontalLayout_15.addWidget(self.gridlineColorBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_15)
        self.label_5 = QtWidgets.QLabel(gridSetupDlg)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineStyleBox = QtWidgets.QComboBox(gridSetupDlg)
        self.lineStyleBox.setObjectName("lineStyleBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineStyleBox)
        self.label_6 = QtWidgets.QLabel(gridSetupDlg)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.cellColorLabel = QtWidgets.QLabel(gridSetupDlg)
        self.cellColorLabel.setMinimumSize(QtCore.QSize(51, 0))
        self.cellColorLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.cellColorLabel.setText("")
        self.cellColorLabel.setObjectName("cellColorLabel")
        self.horizontalLayout_14.addWidget(self.cellColorLabel)
        self.cellColorBtn = QtWidgets.QPushButton(gridSetupDlg)
        self.cellColorBtn.setObjectName("cellColorBtn")
        self.horizontalLayout_14.addWidget(self.cellColorBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_14)
        self.label_7 = QtWidgets.QLabel(gridSetupDlg)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.persistentGridBox = QtWidgets.QCheckBox(gridSetupDlg)
        self.persistentGridBox.setText("")
        self.persistentGridBox.setObjectName("persistentGridBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.persistentGridBox)
        self.label_8 = QtWidgets.QLabel(gridSetupDlg)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.cellBoundaryBox = QtWidgets.QCheckBox(gridSetupDlg)
        self.cellBoundaryBox.setText("")
        self.cellBoundaryBox.setObjectName("cellBoundaryBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cellBoundaryBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.cancelBtn = QtWidgets.QPushButton(gridSetupDlg)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)
        self.okBtn = QtWidgets.QPushButton(gridSetupDlg)
        self.okBtn.setObjectName("okBtn")
        self.horizontalLayout.addWidget(self.okBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(gridSetupDlg)
        QtCore.QMetaObject.connectSlotsByName(gridSetupDlg)

    def retranslateUi(self, gridSetupDlg):
        _translate = QtCore.QCoreApplication.translate
        gridSetupDlg.setWindowTitle(_translate("gridSetupDlg", "Grid Setup"))
        self.label_2.setText(_translate("gridSetupDlg", "Grid Size"))
        self.label_4.setText(_translate("gridSetupDlg", "Line Thickness"))
        self.label_3.setText(_translate("gridSetupDlg", "Radomize Cell"))
        self.label.setText(_translate("gridSetupDlg", "Grid Line Color"))
        self.gridlineColorBtn.setText(_translate("gridSetupDlg", "Select color"))
        self.label_5.setText(_translate("gridSetupDlg", "Grid Line Style"))
        self.label_6.setText(_translate("gridSetupDlg", "Cell Color"))
        self.cellColorBtn.setText(_translate("gridSetupDlg", "Select color"))
        self.label_7.setText(_translate("gridSetupDlg", "Persistent Grid?"))
        self.label_8.setText(_translate("gridSetupDlg", "Enforce Cell Boundary?"))
        self.cancelBtn.setText(_translate("gridSetupDlg", "Cancel"))
        self.okBtn.setText(_translate("gridSetupDlg", "OK"))
