# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\WPy64-3740\SEBASTES\application\dialogs\ui\KeyboardSetupDlg.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_keyboardSetupDlg(object):
    def setupUi(self, keyboardSetupDlg):
        keyboardSetupDlg.setObjectName("keyboardSetupDlg")
        keyboardSetupDlg.resize(294, 464)
        self.formLayout_2 = QtWidgets.QFormLayout(keyboardSetupDlg)
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout)
        self.lineEdit_1 = QtWidgets.QLineEdit(keyboardSetupDlg)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lineEdit_1)
        self.label_1 = QtWidgets.QLabel(keyboardSetupDlg)
        self.label_1.setObjectName("label_1")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_1)
        self.lineEdit_2 = QtWidgets.QLineEdit(keyboardSetupDlg)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lineEdit_2)
        self.label_2 = QtWidgets.QLabel(keyboardSetupDlg)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(keyboardSetupDlg)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lineEdit_3)
        self.label_3 = QtWidgets.QLabel(keyboardSetupDlg)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(keyboardSetupDlg)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lineEdit_4)
        self.label_4 = QtWidgets.QLabel(keyboardSetupDlg)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(keyboardSetupDlg)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lineEdit_5)
        self.label_5 = QtWidgets.QLabel(keyboardSetupDlg)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.label_5)
        self.label_01 = QtWidgets.QLabel(keyboardSetupDlg)
        self.label_01.setObjectName("label_01")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_01)
        self.label_00 = QtWidgets.QLabel(keyboardSetupDlg)
        self.label_00.setObjectName("label_00")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_00)
        self.lineEdit_6 = QtWidgets.QLineEdit(keyboardSetupDlg)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lineEdit_6)
        self.label_6 = QtWidgets.QLabel(keyboardSetupDlg)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.label_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(keyboardSetupDlg)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lineEdit_7)
        self.label_7 = QtWidgets.QLabel(keyboardSetupDlg)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.label_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(keyboardSetupDlg)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.lineEdit_8)
        self.lineEdit_9 = QtWidgets.QLineEdit(keyboardSetupDlg)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.lineEdit_9)
        self.lineEdit_10 = QtWidgets.QLineEdit(keyboardSetupDlg)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.lineEdit_10)
        self.lineEdit_11 = QtWidgets.QLineEdit(keyboardSetupDlg)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.lineEdit_11)
        self.lineEdit_12 = QtWidgets.QLineEdit(keyboardSetupDlg)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.lineEdit_12)
        self.lineEdit_13 = QtWidgets.QLineEdit(keyboardSetupDlg)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.lineEdit_13)
        self.lineEdit_14 = QtWidgets.QLineEdit(keyboardSetupDlg)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.lineEdit_14)
        self.lineEdit_15 = QtWidgets.QLineEdit(keyboardSetupDlg)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.formLayout_2.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.lineEdit_15)
        self.label_8 = QtWidgets.QLabel(keyboardSetupDlg)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(keyboardSetupDlg)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(keyboardSetupDlg)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(keyboardSetupDlg)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(keyboardSetupDlg)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(keyboardSetupDlg)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(keyboardSetupDlg)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(keyboardSetupDlg)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.label_15)
        self.cancelBtn = QtWidgets.QPushButton(keyboardSetupDlg)
        self.cancelBtn.setObjectName("cancelBtn")
        self.formLayout_2.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.cancelBtn)
        self.saveBtn = QtWidgets.QPushButton(keyboardSetupDlg)
        self.saveBtn.setObjectName("saveBtn")
        self.formLayout_2.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.saveBtn)

        self.retranslateUi(keyboardSetupDlg)
        QtCore.QMetaObject.connectSlotsByName(keyboardSetupDlg)

    def retranslateUi(self, keyboardSetupDlg):
        _translate = QtCore.QCoreApplication.translate
        keyboardSetupDlg.setWindowTitle(_translate("keyboardSetupDlg", "Keyboard Setup"))
        self.label_1.setText(_translate("keyboardSetupDlg", "TextLabel"))
        self.label_2.setText(_translate("keyboardSetupDlg", "TextLabel"))
        self.label_3.setText(_translate("keyboardSetupDlg", "TextLabel"))
        self.label_4.setText(_translate("keyboardSetupDlg", "TextLabel"))
        self.label_5.setText(_translate("keyboardSetupDlg", "TextLabel"))
        self.label_01.setText(_translate("keyboardSetupDlg", "Keyboard key"))
        self.label_00.setText(_translate("keyboardSetupDlg", "class"))
        self.label_6.setText(_translate("keyboardSetupDlg", "TextLabel"))
        self.label_7.setText(_translate("keyboardSetupDlg", "TextLabel"))
        self.label_8.setText(_translate("keyboardSetupDlg", "TextLabel"))
        self.label_9.setText(_translate("keyboardSetupDlg", "TextLabel"))
        self.label_10.setText(_translate("keyboardSetupDlg", "TextLabel"))
        self.label_11.setText(_translate("keyboardSetupDlg", "TextLabel"))
        self.label_12.setText(_translate("keyboardSetupDlg", "TextLabel"))
        self.label_13.setText(_translate("keyboardSetupDlg", "TextLabel"))
        self.label_14.setText(_translate("keyboardSetupDlg", "TextLabel"))
        self.label_15.setText(_translate("keyboardSetupDlg", "TextLabel"))
        self.cancelBtn.setText(_translate("keyboardSetupDlg", "Cancel"))
        self.saveBtn.setText(_translate("keyboardSetupDlg", "Save"))
