# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\SEBASTES\SEBASTES_Python-3.7\applications\SEBASTES\application\dialogs\ui\ViewApplicationDBDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_viewApplicationDB(object):
    def setupUi(self, viewApplicationDB):
        viewApplicationDB.setObjectName("viewApplicationDB")
        viewApplicationDB.resize(681, 542)
        self.verticalLayout = QtWidgets.QVBoxLayout(viewApplicationDB)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabs = QtWidgets.QTabWidget(viewApplicationDB)
        self.tabs.setObjectName("tabs")
        self.projects = QtWidgets.QWidget()
        self.projects.setObjectName("projects")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.projects)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.projectsView = QtWidgets.QTableView(self.projects)
        self.projectsView.setObjectName("projectsView")
        self.verticalLayout_2.addWidget(self.projectsView)
        self.tabs.addTab(self.projects, "")
        self.profiles = QtWidgets.QWidget()
        self.profiles.setObjectName("profiles")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.profiles)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.profilesView = QtWidgets.QTableView(self.profiles)
        self.profilesView.setObjectName("profilesView")
        self.verticalLayout_3.addWidget(self.profilesView)
        self.tabs.addTab(self.profiles, "")
        self.profile_settings = QtWidgets.QWidget()
        self.profile_settings.setObjectName("profile_settings")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.profile_settings)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.profileSettingsView = QtWidgets.QTableView(self.profile_settings)
        self.profileSettingsView.setObjectName("profileSettingsView")
        self.verticalLayout_4.addWidget(self.profileSettingsView)
        self.tabs.addTab(self.profile_settings, "")
        self.metadata_groups = QtWidgets.QWidget()
        self.metadata_groups.setObjectName("metadata_groups")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.metadata_groups)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.metadataGroupsView = QtWidgets.QTableView(self.metadata_groups)
        self.metadataGroupsView.setObjectName("metadataGroupsView")
        self.verticalLayout_5.addWidget(self.metadataGroupsView)
        self.tabs.addTab(self.metadata_groups, "")
        self.frame_metadata_setup = QtWidgets.QWidget()
        self.frame_metadata_setup.setObjectName("frame_metadata_setup")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_metadata_setup)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frameMetadataSetupView = QtWidgets.QTableView(self.frame_metadata_setup)
        self.frameMetadataSetupView.setObjectName("frameMetadataSetupView")
        self.verticalLayout_6.addWidget(self.frameMetadataSetupView)
        self.tabs.addTab(self.frame_metadata_setup, "")
        self.species_collections = QtWidgets.QWidget()
        self.species_collections.setObjectName("species_collections")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.species_collections)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.speciesCollectionsView = QtWidgets.QTableView(self.species_collections)
        self.speciesCollectionsView.setObjectName("speciesCollectionsView")
        self.verticalLayout_7.addWidget(self.speciesCollectionsView)
        self.tabs.addTab(self.species_collections, "")
        self.species_setup = QtWidgets.QWidget()
        self.species_setup.setObjectName("species_setup")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.species_setup)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.speciesSetupView = QtWidgets.QTableView(self.species_setup)
        self.speciesSetupView.setObjectName("speciesSetupView")
        self.verticalLayout_8.addWidget(self.speciesSetupView)
        self.tabs.addTab(self.species_setup, "")
        self.verticalLayout.addWidget(self.tabs)

        self.retranslateUi(viewApplicationDB)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(viewApplicationDB)

    def retranslateUi(self, viewApplicationDB):
        _translate = QtCore.QCoreApplication.translate
        viewApplicationDB.setWindowTitle(_translate("viewApplicationDB", "Dialog"))
        self.tabs.setTabText(self.tabs.indexOf(self.projects), _translate("viewApplicationDB", "Projects"))
        self.tabs.setTabText(self.tabs.indexOf(self.profiles), _translate("viewApplicationDB", "Profiles"))
        self.tabs.setTabText(self.tabs.indexOf(self.profile_settings), _translate("viewApplicationDB", "Profile Settings"))
        self.tabs.setTabText(self.tabs.indexOf(self.metadata_groups), _translate("viewApplicationDB", "Metadata Groups"))
        self.tabs.setTabText(self.tabs.indexOf(self.frame_metadata_setup), _translate("viewApplicationDB", "Frame Metadata Setup"))
        self.tabs.setTabText(self.tabs.indexOf(self.species_collections), _translate("viewApplicationDB", "Species Collections"))
        self.tabs.setTabText(self.tabs.indexOf(self.species_setup), _translate("viewApplicationDB", "Species Setup"))
